import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>@vercel/og test app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>@vercel/og Test App</h1>
        <div className='main-links'>
          <Link href="/api/og-vercel">@vercel/og example</Link>
          <Link href="/api/og-next">next/server example</Link>
          <Link href="/api/og-custom">next/server example with a custom font</Link>
        </div>
      </main>
    </>
  )
}
