"use client";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Component, ReactNode, StrictMode } from "react";
// @ts-ignore
import confetti from "https://cdn.skypack.dev/canvas-confetti";
import { useEffect } from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

class P extends Component {
  // eslint-disable-next-line react/no-deprecated
  componentWillMount(): void {
    const test = {};
    // @ts-ignore
    test.thisShouldMakeTsFail = 1;
    console.log("component will mount!");
  }

  render(): ReactNode {
    return <p>This is a Class Component!</p>;
  }
}

export default function Home() {
  useEffect(() => {
    confetti();
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <StrictMode>
          <P />
        </StrictMode>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <Link
            href="markdown"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Markdown <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              A simple page implemented using mdx
            </p>
          </Link>

          <Link
            href="dynamic/test"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Dynamic <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              A very simple dynamic route page
            </p>
          </Link>
        </div>
      </main>
    </>
  );
}
